workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Upgrade Gradle and Build APK
        script: |
          # Gradle wrapper fayllarini aynan talab qilingan 9.3.1 versiyada yaratamiz
          gradle wrapper --gradle-version 9.3.1
          
          # Unga ruxsat beramiz va build boshlaymiz
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
