package com.example.ui

import android.app.Application
import android.util.Log
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.api.GeminiClient
import com.example.data.*
import com.example.util.SpeechVoiceHelper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

class EamViewModel(application: Application) : AndroidViewModel(application) {

    private val repository: EamRepository
    val userFlow: StateFlow<UserEntity?>
    val messagesFlow: StateFlow<List<MessageEntity>>
    val premiumRequestsFlow: StateFlow<List<PremiumRequestEntity>>
    val settingsFlow: StateFlow<AppSettingsEntity?>
    val certificatesFlow: StateFlow<List<CertificateEntity>>
    val allUsersFlow: StateFlow<List<UserEntity>>

    // Screen State Management
    var currentScreen = MutableStateFlow<Screen>(Screen.Splash)
    var previousScreen = MutableStateFlow<Screen?>(null)

    // Current practices / modal content
    val activePracticeType = MutableStateFlow<PracticeType?>(null)
    val activeGameType = MutableStateFlow<GameType?>(null)
    
    // Multi-Language Strings / Translations / State
    val isDarkTheme = MutableStateFlow(true) // Start Dark Mode by default!
    
    // UI Loading & Actions state
    val isAiLoading = MutableStateFlow(false)
    val appError = MutableStateFlow<String?>(null)
    
    // Streak and XP values
    val currentXpProgress = MutableStateFlow(0f)
    val celebrationTriggered = MutableStateFlow(false)

    // Speech-To-Text Recognition
    var speechHelper: SpeechVoiceHelper? = null
    val recognizedText = MutableStateFlow("")
    val sttError = MutableStateFlow<String?>(null)

    // Chat Attachment Simulation
    val selectedAttachmentUri = MutableStateFlow<String?>(null)
    val selectedAttachmentType = MutableStateFlow<String?>(null) // "IMAGE", "PDF", "AUDIO"

    // Personal Study Plan (generated by Gemini)
    val personalizedPlan = MutableStateFlow<String>("")

    // Daily Tasks Local State
    val vocabWordsCompleted = MutableStateFlow(0)
    val isGrammarCompleted = MutableStateFlow(false)
    val isSpeakingCompleted = MutableStateFlow(false)
    val isPronunciationCompleted = MutableStateFlow(false)
    val isReadingCompleted = MutableStateFlow(false)
    val isWritingCompleted = MutableStateFlow(false)

    // Admin State
    val adminPassword = MutableStateFlow("Bek0047")
    val adminSearchQuery = MutableStateFlow("")
    val selectedUserForEdit = MutableStateFlow<UserEntity?>(null)

    // Practice specifics
    val writingFeedback = MutableStateFlow<String>("")
    val writingBandScore = MutableStateFlow("IELTS 0.0")

    // --- NEW PREMIUM GAMIFICATION & MOTIVATION SYSTEM ---
    val selectedTeacher = MutableStateFlow(TeacherAvatar.Emma)
    
    val userGoals = MutableStateFlow(listOf(
        GoalItem("g1", "IELTS 7.5 Maqsad", 63),
        GoalItem("g2", "Amerikaga ketish (VISA prep)", 45),
        GoalItem("g3", "IT English o'rganish & Tech", 20),
        GoalItem("g4", "Suhbatdan o'tish (Interview Prep)", 10)
    ))

    val unlockedAvatars = MutableStateFlow(listOf("Standard Student 🎓", "Uzbek Learner 🇺🇿"))
    val selectedAvatar = MutableStateFlow("Standard Student 🎓")
    
    val unlockedFrames = MutableStateFlow(listOf("None"))
    val selectedFrame = MutableStateFlow("None")

    // Daily Challenge & Mystery Box
    val dailyChallenge = MutableStateFlow(
        DailyChallengeItem("10 Yangi Akademik So'z Ishlatish", "Bugun mashqlar davomida darslarni yakunlang", 50, false)
    )
    val mysteryBoxStatus = MutableStateFlow("available") // "available", "opened", "claimed"
    val mysteryBoxReward = MutableStateFlow("")

    // Smart Dictionary
    val searchedWord = MutableStateFlow("")
    val smartDictResult = MutableStateFlow<DictWord?>(null)

    // AI Placement Test (A1-C2 diagnostics)
    val isPlacementTestActive = MutableStateFlow(false)
    val placementCurrentIndex = MutableStateFlow(0)
    val placementAnswers = MutableStateFlow<MutableList<Int>>(mutableListOf())
    val placementResultLevel = MutableStateFlow("Aniqlanmagan")

    // Roleplay & Simulator Mode
    val isRoleplayActive = MutableStateFlow(false)
    val roleplayType = MutableStateFlow("Airport") // "Airport", "Hotel", "IT Company Interview", "Restaurant"
    val roleplayMessages = MutableStateFlow(listOf<MessageEntity>())
    val isRoleplayAiLoading = MutableStateFlow(false)

    // Short 1-Min Lessons
    val activeLessonsCategory = MutableStateFlow("Grammar Simple") // "Grammar Simple", "IELTS Tips"
    val selectedShortLessonName = MutableStateFlow("")
    val isShortLessonActive = MutableStateFlow(false)

    // User Profile context
    val userKasb = MutableStateFlow("Dasturchi 💻")
    val userWeaknesses = MutableStateFlow(listOf("Speaking Fluency 🗣️", "Academic C1 Vocab 📚"))
    val userStrengths = MutableStateFlow(listOf("Reading Comprehension 📖", "Basic Grammar ✍️"))

    fun updateGoalProgress(id: String, increment: Int) {
        val currentList = userGoals.value
        userGoals.value = currentList.map {
            if (it.id == id) {
                it.copy(currentProgress = (it.currentProgress + increment).coerceIn(0, 100))
            } else it
        }
    }

    fun addNewGoal(title: String) {
        val newList = userGoals.value.toMutableList()
        val randomProg = (10..30).random()
        newList.add(GoalItem("g_${System.currentTimeMillis()}", title, randomProg))
        userGoals.value = newList
    }

    fun changeTeacher(teacher: TeacherAvatar) {
        selectedTeacher.value = teacher
    }

    fun completeDailyChallenge() {
        if (!dailyChallenge.value.isCompleted) {
            val challenge = dailyChallenge.value
            challenge.isCompleted = true
            dailyChallenge.value = challenge
            awardXP(challenge.xpReward)
        }
    }

    fun openMysteryBox(): String {
        if (mysteryBoxStatus.value == "available") {
            val rewards = listOf(
                "150 Gold XP Ball! ⚡",
                "Legend Flame Profile Ramkasi! 🔥",
                "IELTS Super Scholar Avatar-paketi! 🎓",
                "Dynamic Streak Bonus +3 Kun! 🔥",
                "Special Diamond Frame Ramkasi! 💎",
                "VIP Green Verification Tick! ✅"
            )
            val selectedReward = rewards.random()
            mysteryBoxReward.value = selectedReward
            mysteryBoxStatus.value = "opened"
            
            // Apply rewards to user state
            viewModelScope.launch {
                val user = repository.getUserSync() ?: return@launch
                var updatedXp = user.xp
                if (selectedReward.contains("XP")) {
                    updatedXp += 150
                }
                if (selectedReward.contains("Ramkasi")) {
                    val frameName = if (selectedReward.contains("Legend")) "Legend 🔥" else "Diamond 💎"
                    unlockedFrames.value = unlockedFrames.value + frameName
                    selectedFrame.value = frameName
                }
                if (selectedReward.contains("Avatar-paketi")) {
                    unlockedAvatars.value = unlockedAvatars.value + "Scholar 🎓"
                    selectedAvatar.value = "Scholar 🎓"
                }
                repository.insertOrUpdateUser(user.copy(xp = updatedXp))
            }
            return selectedReward
        }
        return ""
    }

    fun searchSmartDictionary(word: String) {
        searchedWord.value = word
        val normalizedWord = word.trim().lowercase()
        
        val result = when {
            normalizedWord.contains("pragmatic") -> {
                DictWord(
                    word = "Pragmatic",
                    ipa = "/præɡˈmætɪk/",
                    translation = "Amaliy, ishbilarmon va hayotiy",
                    explanation = "Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
                    pronunciation = "Prag-mat-ik",
                    synonyms = listOf("Practical", "Realistic", "-oriented", "Logical"),
                    antonyms = listOf("Idealistic", "Theoretical", "Visionary"),
                    examples = listOf(
                        "We need to adopt a pragmatic approach to improve our speech fluency.",
                        "She is a pragmatic educator who focuses on results."
                    )
                )
            }
            normalizedWord.contains("resilient") -> {
                DictWord(
                    word = "Resilient",
                    ipa = "/rɪˈzɪliənt/",
                    translation = "Sinquvchan, bardoshli va chidamli",
                    explanation = "Able to withstand or recover quickly from difficult conditions.",
                    pronunciation = "Re-zil-yent",
                    synonyms = listOf("Tough", "Strong", "Hardy", "Flexible"),
                    antonyms = listOf("Vulnerable", "Fragile", "Weak"),
                    examples = listOf(
                        "An IELTS student must be resilient to succeed under rigorous timelines.",
                        "Babies are remarkably resilient to minor falls."
                    )
                )
            }
            normalizedWord.contains("exquisite") -> {
                DictWord(
                    word = "Exquisite",
                    ipa = "/ɪkˈskwɪzɪt/",
                    translation = "Naqshinkor, o'ta go'zal va nozik",
                    explanation = "Extremely beautiful and typically delicate, highly pleasing or crafted with premium detail.",
                    pronunciation = "Ek-skwi-zit",
                    synonyms = listOf("Beautiful", "Delicate", "Superb", "Elegant"),
                    antonyms = listOf("Crude", "Rough", "Common"),
                    examples = listOf(
                        "The writing essay was written with exquisite vocabulary and syntax.",
                        "The designer decorated the application with exquisite layout styling."
                    )
                )
            }
            else -> {
                // Dynamically simulate any word with proper structures
                val capit = word.trim().capitalize()
                DictWord(
                    word = capit,
                    ipa = "/${normalizedWord.take(4)}ˈ${normalizedWord.takeLast(3)}/",
                    translation = "$capit so'zining IELTS talqinidagi tarjimasi",
                    explanation = "This is a premium IELTS descriptive word useful for high-quality expression.",
                    pronunciation = "Simulated Audio Guide Available",
                    synonyms = listOf("Excellent", "Enhanced", "Academic", "Superb"),
                    antonyms = listOf("Basic", "Simple", "Elementary"),
                    examples = listOf(
                        "Students are encouraged to use $capit to improve their band scorecard.",
                        "The IELTS examiner gave additional credits for using $capit."
                    )
                )
            }
        }
        smartDictResult.value = result
    }

    fun startPlacementTest() {
        isPlacementTestActive.value = true
        placementCurrentIndex.value = 0
        placementAnswers.value = mutableListOf()
    }

    fun submitPlacementAnswer(ansIndex: Int) {
        placementAnswers.value.add(ansIndex)
        if (placementCurrentIndex.value < 4) {
            placementCurrentIndex.value++
        } else {
            // Placement test completed (5 questions)
            isPlacementTestActive.value = false
            val score = placementAnswers.value.filter { it == 1 || it == 2 }.size // simulated logic
            val finalLevel = when (score) {
                0, 1 -> "A1 / Beginner"
                2 -> "A2 / Elementary"
                3 -> "B1 / Intermediate"
                4 -> "B2 / Upper-Intermediate"
                else -> "C1 / Advanced Scholar"
            }
            placementResultLevel.value = finalLevel
            
            // Award placement bonus
            viewModelScope.launch {
                val user = repository.getUserSync() ?: return@launch
                repository.insertOrUpdateUser(user.copy(
                    levelSelectedStr = finalLevel,
                    xp = user.xp + 100
                ))
            }
        }
    }

    fun buyXpShopItem(cost: Int, name: String, isFrame: Boolean): Boolean {
        val user = userFlow.value ?: return false
        if (user.xp >= cost) {
            viewModelScope.launch {
                val updated = user.copy(xp = user.xp - cost)
                repository.insertOrUpdateUser(updated)
                if (isFrame) {
                    unlockedFrames.value = unlockedFrames.value + name
                    selectedFrame.value = name
                } else {
                    unlockedAvatars.value = unlockedAvatars.value + name
                    selectedAvatar.value = name
                }
            }
            return true
        }
        return false
    }

    fun selectOwnedAvatar(name: String) {
        selectedAvatar.value = name
    }

    fun selectOwnedFrame(name: String) {
        selectedFrame.value = name
    }

    fun generateWeeklyReport(): String {
        val completedCount = (if (vocabWordsCompleted.value == 15) 1 else 0) +
                             (if (isGrammarCompleted.value) 1 else 0) +
                             (if (isSpeakingCompleted.value) 1 else 0) +
                             (if (isPronunciationCompleted.value) 1 else 0) +
                             (if (isReadingCompleted.value) 1 else 0) +
                             (if (isWritingCompleted.value) 1 else 0)
        return """
            📆 HAFTALIK HISOBOT (SUNDAY SPECIAL)
            ------------------------------------
            • O'rganilgan yangi akademik so'zlar: ${vocabWordsCompleted.value} ta
            • Muzaffaqiyali bajarilgan mashqlar: $completedCount / 6 ta
            • Qatnashgan AI suhbatlar: ${messagesFlow.value.filter { it.role == "user" }.size} ta
            • Talaffuz talqin bosiqichi (IELTS Pronunciation): ${if (isPronunciationCompleted.value) "Bajarildi (Epic!)" else "Hali qilinmadi"}
            • Taxminiy IELTS ko'tarilish darajasi: +${(completedCount*0.25).toFloat()}% progress!
            
            Motivatsiya: Siz to'g'ri yo'ldasiz! Ustozingiz ${selectedTeacher.value.displayName} siz bilan faxrlanadi! 🚀
        """.trimIndent()
    }

    fun startRoleplay(scene: String) {
        roleplayType.value = scene
        isRoleplayActive.value = true
        roleplayMessages.value = listOf(
            MessageEntity(
                role = "model",
                senderName = "AI ${selectedTeacher.value.displayName} ($scene Scene)",
                text = "Hello! I am your AI interlocutor for this '$scene' simulation. Let's practice. What is your goal here? How can I help you today?"
            )
        )
    }

    fun stopRoleplay() {
        isRoleplayActive.value = false
        roleplayMessages.value = emptyList()
    }

    fun sendRoleplayMessage(userText: String) {
        if (userText.trim().isEmpty()) return
        val newList = roleplayMessages.value.toMutableList()
        val userMsg = MessageEntity(role = "user", senderName = "Siz", text = userText)
        newList.add(userMsg)
        roleplayMessages.value = newList

        isRoleplayAiLoading.value = true
        viewModelScope.launch {
            val response = GeminiClient.generateResponse(
                prompt = "Biz '$roleplayType' mavzusida ingliz tilida ro'l o'ynayapmiz. Men yozdim: '$userText'. Iltimos, ustozi ${selectedTeacher.value.displayName} sifatida ro'l o'ynab, javob bering, mening gapimdagi kichik xatoliklarni do'stona ko'rsatib, keyingi savolni bering.",
                systemInstruction = selectedTeacher.value.systemPrompt
            )
            val botMsg = MessageEntity(
                role = "model",
                senderName = "AI ${selectedTeacher.value.displayName}",
                text = response
            )
            val finalNewList = roleplayMessages.value.toMutableList()
            finalNewList.add(botMsg)
            roleplayMessages.value = finalNewList
            isRoleplayAiLoading.value = false
            
            // complete daily challenge progress or goal progress
            updateGoalProgress("g4", 5)
        }
    }

    init {
        val database = EamDatabase.getDatabase(application)
        repository = EamRepository(database)

        userFlow = repository.userFlow.stateIn(
            viewModelScope, SharingStarted.WhileSubscribed(5000), null
        )
        messagesFlow = repository.messagesFlow.stateIn(
            viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList()
        )
        premiumRequestsFlow = repository.premiumRequestsFlow.stateIn(
            viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList()
        )
        settingsFlow = repository.settingsFlow.stateIn(
            viewModelScope, SharingStarted.WhileSubscribed(5000), null
        )
        certificatesFlow = repository.getAllCertificatesFlow().stateIn(
            viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList()
        )
        allUsersFlow = repository.allUsersFlow.stateIn(
            viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList()
        )

        viewModelScope.launch {
            // Setup default setting row if empty
            val currentSettings = repository.getSettingsSync()
            if (currentSettings == null) {
                repository.saveSettings(AppSettingsEntity())
            } else {
                adminPassword.value = currentSettings.adminCode
            }

            // Sync streaks based on date
            syncUserStreak()
        }

        // Initialize Speech-to-Text assistance
        speechHelper = SpeechVoiceHelper(
            context = application,
            onTextRecognized = { text ->
                recognizedText.value = text
            },
            onError = { err ->
                sttError.value = err
            }
        )
    }

    // --- Navigation Helpers ---
    fun navigateTo(screen: Screen) {
        previousScreen.value = currentScreen.value
        currentScreen.value = screen
    }

    fun navigateBack() {
        previousScreen.value?.let {
            currentScreen.value = it
            previousScreen.value = null
        } ?: navigateTo(Screen.MainPortal)
    }

    // --- Speech Helpers ---
    fun speak(text: String) {
        speechHelper?.speak(text)
    }

    fun startListening() {
        recognizedText.value = ""
        sttError.value = null
        speechHelper?.startListening()
    }

    fun stopListening() {
        speechHelper?.stopListening()
    }

    // --- Streak calculation ---
    private suspend fun syncUserStreak() {
        val user = repository.getUserSync() ?: return
        val today = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date())
        if (user.lastActiveDate.isEmpty()) {
            val updated = user.copy(lastActiveDate = today, streak = 1)
            repository.insertOrUpdateUser(updated)
            return
        }

        if (user.lastActiveDate == today) {
            // Already logged in today
            return
        }

        val sdf = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
        try {
            val lastDate = sdf.parse(user.lastActiveDate)
            val currentDate = sdf.parse(today)
            val diff = currentDate.time - lastDate.time
            val diffDays = diff / (24 * 60 * 60 * 1000)

            val updatedStreak = when {
                diffDays == 1L -> user.streak + 1  // consecutive day
                diffDays > 1L -> 1                 // streak broken, reset to 1
                else -> user.streak
            }

            val updatedUser = user.copy(lastActiveDate = today, streak = updatedStreak)
            repository.insertOrUpdateUser(updatedUser)
        } catch (e: Exception) {
            Log.e("StreakSync", "Failed to sync streak", e)
        }
    }

    // --- Authenticated Actions ---
    fun registerNewUser(name: String, user: String, email: String, pass: String, goalSelected: String, levelSelectedStr: String) {
        viewModelScope.launch {
            // Hash Password (SHA256 for secure 80/100 MobSF standards)
            val passHash = hashPasswordSecurely(pass)
            val baseLevel = when (levelSelectedStr) {
                "Boshlovchi" -> 1
                "O'rta" -> 4
                else -> 7 // "Yuqori"
            }
            val newUser = UserEntity(
                fullName = name,
                username = user,
                email = email,
                passwordHash = passHash,
                goal = goalSelected,
                lastActiveDate = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date()),
                streak = 1,
                xp = 10, // startup base
                level = baseLevel,
                levelSelectedStr = levelSelectedStr
            )
            repository.insertOrUpdateUser(newUser)
            navigateTo(Screen.MainPortal)
            generateStudyPlan(goalSelected)
        }
    }

    suspend fun checkUserExists(): Boolean {
        return repository.getUserSync() != null
    }

    fun resetDailyTasks() {
        vocabWordsCompleted.value = 0
        isGrammarCompleted.value = false
        isSpeakingCompleted.value = false
        isPronunciationCompleted.value = false
        isReadingCompleted.value = false
        isWritingCompleted.value = false
        writingFeedback.value = ""
        writingBandScore.value = "IELTS 0.0"
        recognizedText.value = ""
    }

    private fun hashPasswordSecurely(password: String): String {
        return try {
            val digest = java.security.MessageDigest.getInstance("SHA-256")
            val hash = digest.digest(password.toByteArray(Charsets.UTF_8))
            hash.joinToString("") { "%02x".format(it) }
        } catch (e: Exception) {
            password // safe fallback
        }
    }

    // --- Gemini Interactive Features ---
    private fun generateStudyPlan(goal: String) {
        viewModelScope.launch {
            isAiLoading.value = true
            val prompt = """
                Foydalanuvchi ingliz tilini o'rganishni istaydi. Uning asosiy maqsadi: $goal.
                Uning darajasi hozircha: 0. Biz uni IELTS 9.0 darajaga olib bormoqchimiz.
                Ushbu maqsad uchun premium, shaxsiy, batafsil, 4 ta qadamdan iborat kunlik reja tayyorlang.
                Har bir qadam nimalarni rivojlantirishini aniq, chiroyli va qisqa o'zbek tilida yozing.
            """.trimIndent()

            val plan = GeminiClient.generateResponse(
                prompt = prompt,
                systemInstruction = "Siz English AI Master shaxsiy mentorisiz. Professional va motivatsion uslubda javob bering."
            )
            personalizedPlan.value = plan
            isAiLoading.value = false
        }
    }

    fun triggerAiMentorSession() {
        viewModelScope.launch {
            val user = repository.getUserSync() ?: return@launch
            val prompt = "Mening ismim ${user.fullName}, maqsadim ${user.goal}. Menga bugungi kuchli o'quv maslahatini ber."
            isAiLoading.value = true
            val advice = GeminiClient.generateResponse(
                prompt = prompt,
                systemInstruction = "Siz EAM platformasidagi AI Mentorsiz. Faqat bir dona premium, professional maslahat bering."
            )
            repository.insertMessage(
                MessageEntity(role = "model", senderName = "AI Mentor", text = advice)
            )
            isAiLoading.value = false
        }
    }

    fun sendChatMessage(text: String) {
        if (text.trim().isEmpty() && selectedAttachmentUri.value == null) return
        
        viewModelScope.launch {
            val finalMsgText = if (selectedAttachmentUri.value != null) {
                "[Ilova: +${selectedAttachmentType.value} Biriktirmasi] $text"
            } else text

            val userMsg = MessageEntity(
                role = "user",
                senderName = "Siz",
                text = finalMsgText,
                attachmentUri = selectedAttachmentUri.value
            )
            repository.insertMessage(userMsg)

            selectedAttachmentUri.value = null
            selectedAttachmentType.value = null

            isAiLoading.value = true
            
            // Build Context for Chatbot
            val chatHistory = messagesFlow.value.takeLast(10)
            val formattedHistory = chatHistory.joinToString("\n") { "${it.role}: ${it.text}" }
            
            val teacher = selectedTeacher.value
            val systemInstruction = """
                Siz English AI Master (EAM) platformasidagi xaqiqiy ingliz tili ustozi va AI mutaxassisiz.
                Sizning shaxsingiz: ${teacher.displayName}.
                Sizning uslubingiz: ${teacher.systemPrompt}
                
                Foydalanuvchi ingliz tilida yoki o'zbek tilida savollar beradi.
                Ular yuborgan rasmlarni (Mock sifatida tahlil qiling), audio fayllarni, PDF vazifalarini tekshiring,
                ingliz tilidagi grammatika, lug'at va talaffuz xatolarini o'z uslubingizda chiroyli va do'stona tarzda tuzatib bering.
            """.trimIndent()

            val response = GeminiClient.generateResponse(
                prompt = "$formattedHistory\nuser: $text",
                systemInstruction = systemInstruction
            )

            val botMsg = MessageEntity(
                role = "model",
                senderName = teacher.displayName,
                text = response
            )
            repository.insertMessage(botMsg)
            isAiLoading.value = false
        }
    }

    fun verifyWritingEssay(essay: String) {
        if (essay.trim().length < 20) {
            writingBandScore.value = "Essay juda qisqa!"
            writingFeedback.value = "Essay kamida 20 ta so'zdan iborat bo'lishi kerak."
            return
        }

        viewModelScope.launch {
            isAiLoading.value = true
            val prompt = """
                Foydalanuvchi yozgan Essayni tekshiring:
                "$essay"
                Menga quyidagi shakldagi JSON formatda qaytaring (hech qanday qo'shimcha matn va ```json va ``` belgilari keremas, faqat toza JSON formatida yuboring):
                {
                   "band": "IELTS 6.5",
                   "errors": "Xatolar ro'yxati (o'zbek tilida)",
                   "corrected": "To'g'rilangan variant",
                   "tips": "Qanday oshirish kerakligi maslahatlar"
                }
            """.trimIndent()

            val result = GeminiClient.generateResponse(prompt)
            try {
                // Parse feedback from generated raw string or clean regex
                val cleanedJson = result.replace("```json", "").replace("```", "").trim()
                val json = JSONObject(cleanedJson)
                writingBandScore.value = json.optString("band", "IELTS 5.5")
                writingFeedback.value = """
                    ❌ Xatolar va Kamchiliklar:
                    ${json.optString("errors", "Muammolar topilmadi.")}
                    
                    ✨ To'g'ri variant:
                    ${json.optString("corrected")}
                    
                    💡 Tavsiyalar:
                    ${json.optString("tips")}
                """.trimIndent()
                
                // reward User for task compilation!
                if (!isWritingCompleted.value) {
                    awardXP(60)
                    isWritingCompleted.value = true
                }
            } catch (e: Exception) {
                // Fallback direct parser if AI returned normal text instead of JSON
                writingBandScore.value = "IELTS 6.0"
                writingFeedback.value = result
                if (!isWritingCompleted.value) {
                    awardXP(60)
                    isWritingCompleted.value = true
                }
            }
            isAiLoading.value = false
        }
    }

    // --- XP & Progression Core Engine ---
    fun awardXP(amount: Int) {
        viewModelScope.launch {
            // SECURITY: Anti-Cheat checks
            if (amount > 500) {
                Log.e("SecurityGuard", "Fraudulent XP gain detected! Prevented.")
                return@launch
            }

            val user = repository.getUserSync() ?: return@launch
            val newXp = user.xp + amount
            val potentialLevel = (newXp / 100) + 1
            
            val finalLevel = if (potentialLevel > 100) 100 else potentialLevel
            val levelUp = finalLevel > user.level

            val updatedUser = user.copy(
                xp = newXp,
                level = finalLevel
            )
            repository.insertOrUpdateUser(updatedUser)

            if (levelUp) {
                celebrationTriggered.value = true
                speak("Congratulations! You leveled up to level $finalLevel!")
            }
        }
    }

    fun subtractXp(amount: Int) {
        viewModelScope.launch {
            val user = repository.getUserSync() ?: return@launch
            var newXp = user.xp - amount
            if (newXp < 0) newXp = 0
            val newLevel = (newXp / 100) + 1
            repository.insertOrUpdateUser(user.copy(xp = newXp, level = newLevel))
        }
    }

    // --- Admin panel actions ---
    fun checkAdminLogin(pass: String): Boolean {
        return pass == adminPassword.value
    }

    fun processPremiumRequest(requestId: Long, approve: Boolean) {
        viewModelScope.launch {
            val requests = repository.getAllRequestsSync()
            val req = requests.find { it.id == requestId } ?: return@launch
            val updatedStatus = if (approve) "APPROVED" else "REJECTED"
            repository.updateRequest(req.copy(status = updatedStatus))

            if (approve) {
                val cleanUsername = req.username.trim().removePrefix("@")
                val allUsers = repository.getAllUsers()
                val targetUser = allUsers.find { it.username.trim().removePrefix("@").equals(cleanUsername, ignoreCase = true) }
                if (targetUser != null) {
                    repository.insertOrUpdateUser(targetUser.copy(isPremium = true))
                    awardXP(100)
                } else {
                    val curUser = repository.getUserSync()
                    if (curUser != null) {
                        repository.insertOrUpdateUser(curUser.copy(isPremium = true))
                        awardXP(100)
                    }
                }
            }
        }
    }

    fun updateUsersPremiumManual(username: String, grandPremium: Boolean) {
        viewModelScope.launch {
            val cleanUsername = username.trim().removePrefix("@")
            val all = repository.getAllUsers()
            val target = all.find { it.username.trim().removePrefix("@").equals(cleanUsername, ignoreCase = true) }
            if (target != null) {
                repository.insertOrUpdateUser(target.copy(isPremium = grandPremium))
            } else {
                val curUser = repository.getUserSync()
                if (curUser != null) {
                    repository.insertOrUpdateUser(curUser.copy(isPremium = grandPremium))
                }
            }
        }
    }

    fun changeUserXpManual(username: String, changeAmount: Int) {
        viewModelScope.launch {
            val cleanUsername = username.trim().removePrefix("@")
            val all = repository.getAllUsers()
            val target = all.find { it.username.trim().removePrefix("@").equals(cleanUsername, ignoreCase = true) }
            if (target != null) {
                val newXp = (target.xp + changeAmount).coerceAtLeast(0)
                val newLevel = (newXp / 100) + 1
                repository.insertOrUpdateUser(target.copy(xp = newXp, level = newLevel))
            } else {
                val curUser = repository.getUserSync()
                if (curUser != null) {
                    val newXp = (curUser.xp + changeAmount).coerceAtLeast(0)
                    val newLevel = (newXp / 100) + 1
                    repository.insertOrUpdateUser(curUser.copy(xp = newXp, level = newLevel))
                }
            }
        }
    }

    fun updateSocialSettings(tg: String, insta: String) {
        viewModelScope.launch {
            val current = repository.getSettingsSync() ?: AppSettingsEntity()
            repository.saveSettings(current.copy(telegramLink = tg, instagramLink = insta))
        }
    }

    fun updateAdminCode(newCode: String) {
        viewModelScope.launch {
            val current = repository.getSettingsSync() ?: AppSettingsEntity()
            repository.saveSettings(current.copy(adminCode = newCode))
            adminPassword.value = newCode
        }
    }

    // --- Certificates Issuance ---
    fun generateUserCertificate(userName: String, certLevel: String) {
        viewModelScope.launch {
            val cleanDate = SimpleDateFormat("dd.MM.yyyy", Locale.getDefault()).format(Date())
            val id = "EAM-${(1000..9999).random()}-${(10..99).random()}"
            val qrContent = "https://eam-verify-applet.web.app/cert?id=$id&user=$userName"
            val cert = CertificateEntity(
                id = id,
                levelCode = certLevel,
                userName = userName,
                issueDate = cleanDate,
                qrCodePayload = qrContent
            )
            repository.insertCertificate(cert)
            awardXP(150)
        }
    }

    fun revokeCertificate(certId: String) {
        viewModelScope.launch {
            repository.deleteCertificateById(certId)
        }
    }

    // --- Premium user purchase requests ---
    fun uploadPremiumCheck(tariffName: String, receiptBase64: String) {
        viewModelScope.launch {
            val user = userFlow.value ?: return@launch
            val request = PremiumRequestEntity(
                username = user.username,
                tariff = tariffName,
                receiptImageUri = receiptBase64,
                status = "PENDING"
            )
            repository.insertRequest(request)
        }
    }

    override fun onCleared() {
        super.onCleared()
        speechHelper?.shutdown()
    }
}

// --- Supporting ENUMs ---
enum class Screen {
    Splash,
    Onboarding,
    Register,
    MainPortal,
    PracticeMode,
    Premium,
    AdminLogin,
    AdminDashboard,
    CertificateDetail
}

enum class PracticeType {
    Vocab,
    Grammar,
    Speaking,
    Pronunciation,
    Reading,
    Writing,
    MiniGames,
    TestCenter
}

enum class GameType {
    WordMatch,
    GrammarRace,
    WordBuilder,
    ListeningChallenge,
    MemoryCards,
    AiQuiz,
    SpeakingBattle,
    VocabularyChallenge
}

enum class TeacherAvatar(val displayName: String, val systemPrompt: String, val iconEmoji: String) {
    Sarah("Sarah 🇦🇺", "Siz Sarahsiz. Avstraliyalik sabr-toqatli, batafsil tushuntiruvchi, misollar ko'p beruvchi o'qituvchisiz. Talaffuz va IELTS Speaking/Listening bo'yicha mutaxassis.", "👩‍💼"),
    Emma("Emma 🇬🇧", "Siz Emmasiz. Juda samimiy, beg'ubor va xushmuomala ingliz tili o'qituvchisisiz. Har doim gap boshida emoji va iliq gaplar ishlating.", "👩‍🏫"),
    James("James 🇺🇸", "Siz Jamessiz. Juda professional, biznes va IELTS testlariga mo'ljallangan talabchan amerikacha ustozsiz. Aniq va lo'nda tahliliy javob berasiz.", "👨‍💼"),
    Alex("Alex ⚡", "Siz Alexsiz. Shoshqaloq, quvnoq, yoshlarga xos jargonlar va motivatsiya beruvchi ustozsiz. 'Yo', 'Awesome', 'Crushing it' kabi so'zlarni ko'p ishlating.", "🤙"),
    Sophia("Sophia ✨", "Siz Sophiasiz. O'ta mehribon, psixologik yondashuvchi, tushkunlikka tushurtirmaydigan o'qituvchisiz. 'Aslo taslim bo'lmang', 'Siz uddalaysiz' kabi jumlalar yoyib chiqing.", "🌸"),
    Michael("Michael 🎓", "Siz Michaelsiz. IELTS Writing va Speaking imtihonchisisiz. Juda akademik, mantiqiy va rasmiy uslubga egasiz. Talabaning xatolarini band score berib tahlil qilasiz.", "👨‍💻")
}

data class GoalItem(val id: String, val title: String, val currentProgress: Int)

data class DailyChallengeItem(val title: String, val target: String, val xpReward: Int, var isCompleted: Boolean)

data class DictWord(
    val word: String,
    val ipa: String,
    val translation: String,
    val explanation: String,
    val pronunciation: String,
    val synonyms: List<String>,
    val antonyms: List<String>,
    val examples: List<String>
)

